### ISSUE TITLE
Revisão: Documento de Requisitos

### ISSUE THREAD

**Issue by rafaelportomoura** [rafaelportomoura/federacao-lavrense-de-futebol#25]
1 - Editar pós-condições dos diagramas de casos de uso
2 - Revisar fluxos principais no documento de requisitos
3 - (Time) Nome não pode ser vazio, mínimo 3 caracteres maximo 100 e não pode ser repetido
4 - Mais dois passos validar dados, validar transação dos dados no banco de dados
5 - Remover redundância nos fluxos

**Comment by diego-andrade1000** [comment]
Adicionando mais algumas tasks:
-Revisar requisitos não funcionais;
-Revisar regras de verificação e análise de requisitos.
